### ISSUE TITLE
Could not load file or assembly 'IntelHexFormatReader, Version=2.2.3.0, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by lucytang1** [christophediericx/ArduinoSketchUploader#64]
When i try to load a hexfile i get this error

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'IntelHexFormatReader, Version=2.2.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=ArduinoUploader
  StackTrace:
   at ArduinoUploader.ArduinoSketchUploader.UploadSketch(IEnumerable`1 hexFileContents)
   at ArduinoUploader.ArduinoSketchUploader.UploadSketch()
   at Program.Main() in C:\Users\thinkhigh\source\repos\ConsoleApp1\Program.cs:line 17

**Comment by lucytang1** [comment]
installed the latest version of IntelHExformatReader
